apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgCrPqVNBBqK8rrUc+hWRKef0l9DJ3dsHnSqxyHCLsZemw+l548p9sDky0G78xkK215IsHGP2ZDGj2reBbsbSUAQGs/Mjgb6RLKVsYUXO6g/Bm0np8yYTI1DthqRkX+xfMrij6xcqATwz0t6mLbs4o3ZQ/uJ9/K0mTB+aCXGLNvuBy1HesKajzrO6UACkSn9qksb1enbo0h5jyNmksNFe1aCRvHosLZRemZuJs4KEz0hgAVDEG+w/0VvOzDEyrKxNWP8yStmp7Tmq19n0ZoJMPI+LCElYHZUJbuKlBS+bkENat2OTq5aLM8jH9ow+bZnKeER1mLotEEzKwp2Rhip9mSfUplntkj0DwA/RmPuE7Ju2Pwacw/SLFyQsvvdyPZhLx/IuiWXSx5TBmK3HmxFwcGxi0dpniS305pRPCUPx6q1mwR2w30vUyOi6qgONWx+AhIg+nK+TIqsNGa1SkkiAByts15KFeLxmE9mo21Sc/1a+cz0GmDx5gqOR9UomUEtJwZmujENpy+cBzvGTU870ieIbu7QrlNhHeqpM5DGXsRqYfdVKHmLEWh5b8ybQ7krXYnoiFpJ0mP3GSzOv0ur+1gC/tHeWRc8K9LNg9bbynKLJgjCp+014DY3voeBakK8mOUlQze8kidqVpLVkevRtXJVZ+4bjd0cRCHhKcrcx3qeXY45nOXjgEOATOwRv3FHFG/43z6BgC01f4GW2oVLabFzLDiUBSCMvqxwMHP9vpy4zo5zS2WDqpAAtltPtpPK8IGqSYEE3qA/AWEx5qGp+dyhJrFKP7De9RQqgEUXeTbp6j6GDET2AJNMorcEmThUKV1s7YokW7LC5c2Z3OUZ3bA+MuiZLXEFRroOqbV2i6vkO3ahNB8uPXyXW3W7RH81uV7qIc0ytKYS8CcJ8rfD9wQ9Db08vPn7wRKB8jfzgxCGNgzLuknqDtA1x27F9v/A/gLZTfTN/nuwt+tlMXf1ttvs78zlOy/MZ1pbYlwR5D5e39TVaQraeNALsEPH1XDtb5CCXp33f8ZiFBTcByVtjBrcJV7BeUmrqnBOuVGInZWQ7y1+Kyr1GGE7DgD+seqGRNL+hsH2H2LCDsY0VuUH3exFWco3YX5S1YD7twS1ogrzF2F2yNSHNzhtMSglW+KeAKqWgWAK+jEjR8UMhaCic4WgpKJjSNoVTOuRYTcZOu4INWKZegf+bhNTBAr3KjOdQ3uHVFeqXPap1bj7HIcHeRIJdtqq5ky+isdKZCNdjfnidrmciIf9iGoYOQ2CYFnSfAkUxsiNpe7hEvgau/K3zwoyN8Yb9q3Wy6gukY/EbQczGuzZTodDnToYWajnUaX0Cvrs
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

